# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6eb18121583b410ad61540742308b8580d18833fc4355d9d6c30b0792be2177e02168930b97e0db1d9f0b37a2c5a0984e01c9a78e7909c917271158bd0c2d40c

test:
  secret_key_base: 519d4a0ab82b96a7c83e886967a0191aa7a30d1effc4952f96fe838125446f0894cdb23bb02e6bdee4532ea963088f2e5e8b4cabdacce09986eed05882f4c321

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
